import type { SurahMeta } from "./types";

/** Complete 114 Surahs metadata (Madani mushaf page approx) */
export const SURAHS: SurahMeta[] = [
  { number: 1, nameAr: "الفاتحة", nameEn: "Al-Fatihah", nameTransliteration: "Al-Faatiha", ayahCount: 7, revelationType: "Meccan", startPage: 1, endPage: 1, startJuz: 1 },
  { number: 2, nameAr: "البقرة", nameEn: "Al-Baqarah", nameTransliteration: "Al-Baqara", ayahCount: 286, revelationType: "Medinan", startPage: 2, endPage: 49, startJuz: 1 },
  { number: 3, nameAr: "آل عمران", nameEn: "Aal-Imran", nameTransliteration: "Aal-i-Imraan", ayahCount: 200, revelationType: "Medinan", startPage: 50, endPage: 76, startJuz: 3 },
  { number: 4, nameAr: "النساء", nameEn: "An-Nisa", nameTransliteration: "An-Nisaa", ayahCount: 176, revelationType: "Medinan", startPage: 77, endPage: 106, startJuz: 4 },
  { number: 5, nameAr: "المائدة", nameEn: "Al-Ma'idah", nameTransliteration: "Al-Maaida", ayahCount: 120, revelationType: "Medinan", startPage: 106, endPage: 127, startJuz: 6 },
  { number: 6, nameAr: "الأنعام", nameEn: "Al-An'am", nameTransliteration: "Al-An'aam", ayahCount: 165, revelationType: "Meccan", startPage: 128, endPage: 150, startJuz: 7 },
  { number: 7, nameAr: "الأعراف", nameEn: "Al-A'raf", nameTransliteration: "Al-A'raaf", ayahCount: 206, revelationType: "Meccan", startPage: 151, endPage: 176, startJuz: 8 },
  { number: 8, nameAr: "الأنفال", nameEn: "Al-Anfal", nameTransliteration: "Al-Anfaal", ayahCount: 75, revelationType: "Medinan", startPage: 177, endPage: 186, startJuz: 9 },
  { number: 9, nameAr: "التوبة", nameEn: "At-Tawbah", nameTransliteration: "At-Tawba", ayahCount: 129, revelationType: "Medinan", startPage: 187, endPage: 207, startJuz: 10 },
  { number: 10, nameAr: "يونس", nameEn: "Yunus", nameTransliteration: "Yunus", ayahCount: 109, revelationType: "Meccan", startPage: 208, endPage: 221, startJuz: 11 },
  { number: 11, nameAr: "هود", nameEn: "Hud", nameTransliteration: "Hud", ayahCount: 123, revelationType: "Meccan", startPage: 221, endPage: 235, startJuz: 11 },
  { number: 12, nameAr: "يوسف", nameEn: "Yusuf", nameTransliteration: "Yusuf", ayahCount: 111, revelationType: "Meccan", startPage: 235, endPage: 248, startJuz: 12 },
  { number: 13, nameAr: "الرعد", nameEn: "Ar-Ra'd", nameTransliteration: "Ar-Ra'd", ayahCount: 43, revelationType: "Medinan", startPage: 249, endPage: 255, startJuz: 13 },
  { number: 14, nameAr: "إبراهيم", nameEn: "Ibrahim", nameTransliteration: "Ibrahim", ayahCount: 52, revelationType: "Meccan", startPage: 255, endPage: 261, startJuz: 13 },
  { number: 15, nameAr: "الحجر", nameEn: "Al-Hijr", nameTransliteration: "Al-Hijr", ayahCount: 99, revelationType: "Meccan", startPage: 262, endPage: 267, startJuz: 14 },
  { number: 16, nameAr: "النحل", nameEn: "An-Nahl", nameTransliteration: "An-Nahl", ayahCount: 128, revelationType: "Meccan", startPage: 267, endPage: 281, startJuz: 14 },
  { number: 17, nameAr: "الإسراء", nameEn: "Al-Isra", nameTransliteration: "Al-Israa", ayahCount: 111, revelationType: "Meccan", startPage: 282, endPage: 293, startJuz: 15 },
  { number: 18, nameAr: "الكهف", nameEn: "Al-Kahf", nameTransliteration: "Al-Kahf", ayahCount: 110, revelationType: "Meccan", startPage: 293, endPage: 304, startJuz: 15 },
  { number: 19, nameAr: "مريم", nameEn: "Maryam", nameTransliteration: "Maryam", ayahCount: 98, revelationType: "Meccan", startPage: 305, endPage: 312, startJuz: 16 },
  { number: 20, nameAr: "طه", nameEn: "Ta-Ha", nameTransliteration: "Taa-Haa", ayahCount: 135, revelationType: "Meccan", startPage: 312, endPage: 321, startJuz: 16 },
  { number: 21, nameAr: "الأنبياء", nameEn: "Al-Anbiya", nameTransliteration: "Al-Anbiyaa", ayahCount: 112, revelationType: "Meccan", startPage: 322, endPage: 331, startJuz: 17 },
  { number: 22, nameAr: "الحج", nameEn: "Al-Hajj", nameTransliteration: "Al-Hajj", ayahCount: 78, revelationType: "Medinan", startPage: 332, endPage: 341, startJuz: 17 },
  { number: 23, nameAr: "المؤمنون", nameEn: "Al-Mu'minun", nameTransliteration: "Al-Muminoon", ayahCount: 118, revelationType: "Meccan", startPage: 342, endPage: 349, startJuz: 18 },
  { number: 24, nameAr: "النور", nameEn: "An-Nur", nameTransliteration: "An-Noor", ayahCount: 64, revelationType: "Medinan", startPage: 350, endPage: 359, startJuz: 18 },
  { number: 25, nameAr: "الفرقان", nameEn: "Al-Furqan", nameTransliteration: "Al-Furqaan", ayahCount: 77, revelationType: "Meccan", startPage: 359, endPage: 366, startJuz: 18 },
  { number: 26, nameAr: "الشعراء", nameEn: "Ash-Shu'ara", nameTransliteration: "Ash-Shu'araa", ayahCount: 227, revelationType: "Meccan", startPage: 367, endPage: 376, startJuz: 19 },
  { number: 27, nameAr: "النمل", nameEn: "An-Naml", nameTransliteration: "An-Naml", ayahCount: 93, revelationType: "Meccan", startPage: 377, endPage: 385, startJuz: 19 },
  { number: 28, nameAr: "القصص", nameEn: "Al-Qasas", nameTransliteration: "Al-Qasas", ayahCount: 88, revelationType: "Meccan", startPage: 385, endPage: 396, startJuz: 20 },
  { number: 29, nameAr: "العنكبوت", nameEn: "Al-Ankabut", nameTransliteration: "Al-Ankaboot", ayahCount: 69, revelationType: "Meccan", startPage: 396, endPage: 404, startJuz: 20 },
  { number: 30, nameAr: "الروم", nameEn: "Ar-Rum", nameTransliteration: "Ar-Room", ayahCount: 60, revelationType: "Meccan", startPage: 404, endPage: 410, startJuz: 21 },
  { number: 31, nameAr: "لقمان", nameEn: "Luqman", nameTransliteration: "Luqman", ayahCount: 34, revelationType: "Meccan", startPage: 411, endPage: 414, startJuz: 21 },
  { number: 32, nameAr: "السجدة", nameEn: "As-Sajdah", nameTransliteration: "As-Sajda", ayahCount: 30, revelationType: "Meccan", startPage: 415, endPage: 417, startJuz: 21 },
  { number: 33, nameAr: "الأحزاب", nameEn: "Al-Ahzab", nameTransliteration: "Al-Ahzaab", ayahCount: 73, revelationType: "Medinan", startPage: 418, endPage: 427, startJuz: 21 },
  { number: 34, nameAr: "سبأ", nameEn: "Saba", nameTransliteration: "Saba", ayahCount: 54, revelationType: "Meccan", startPage: 428, endPage: 434, startJuz: 22 },
  { number: 35, nameAr: "فاطر", nameEn: "Fatir", nameTransliteration: "Faatir", ayahCount: 45, revelationType: "Meccan", startPage: 434, endPage: 440, startJuz: 22 },
  { number: 36, nameAr: "يس", nameEn: "Ya-Sin", nameTransliteration: "Yaseen", ayahCount: 83, revelationType: "Meccan", startPage: 440, endPage: 445, startJuz: 22 },
  { number: 37, nameAr: "الصافات", nameEn: "As-Saffat", nameTransliteration: "As-Saaffaat", ayahCount: 182, revelationType: "Meccan", startPage: 446, endPage: 452, startJuz: 23 },
  { number: 38, nameAr: "ص", nameEn: "Sad", nameTransliteration: "Saad", ayahCount: 88, revelationType: "Meccan", startPage: 453, endPage: 458, startJuz: 23 },
  { number: 39, nameAr: "الزمر", nameEn: "Az-Zumar", nameTransliteration: "Az-Zumar", ayahCount: 75, revelationType: "Meccan", startPage: 458, endPage: 467, startJuz: 23 },
  { number: 40, nameAr: "غافر", nameEn: "Ghafir", nameTransliteration: "Ghafir", ayahCount: 85, revelationType: "Meccan", startPage: 467, endPage: 476, startJuz: 24 },
  { number: 41, nameAr: "فصلت", nameEn: "Fussilat", nameTransliteration: "Fussilat", ayahCount: 54, revelationType: "Meccan", startPage: 477, endPage: 482, startJuz: 24 },
  { number: 42, nameAr: "الشورى", nameEn: "Ash-Shura", nameTransliteration: "Ash-Shura", ayahCount: 53, revelationType: "Meccan", startPage: 483, endPage: 489, startJuz: 25 },
  { number: 43, nameAr: "الزخرف", nameEn: "Az-Zukhruf", nameTransliteration: "Az-Zukhruf", ayahCount: 89, revelationType: "Meccan", startPage: 489, endPage: 495, startJuz: 25 },
  { number: 44, nameAr: "الدخان", nameEn: "Ad-Dukhan", nameTransliteration: "Ad-Dukhaan", ayahCount: 59, revelationType: "Meccan", startPage: 496, endPage: 498, startJuz: 25 },
  { number: 45, nameAr: "الجاثية", nameEn: "Al-Jathiyah", nameTransliteration: "Al-Jaathiya", ayahCount: 37, revelationType: "Meccan", startPage: 499, endPage: 502, startJuz: 25 },
  { number: 46, nameAr: "الأحقاف", nameEn: "Al-Ahqaf", nameTransliteration: "Al-Ahqaf", ayahCount: 35, revelationType: "Meccan", startPage: 502, endPage: 506, startJuz: 26 },
  { number: 47, nameAr: "محمد", nameEn: "Muhammad", nameTransliteration: "Muhammad", ayahCount: 38, revelationType: "Medinan", startPage: 507, endPage: 510, startJuz: 26 },
  { number: 48, nameAr: "الفتح", nameEn: "Al-Fath", nameTransliteration: "Al-Fath", ayahCount: 29, revelationType: "Medinan", startPage: 511, endPage: 515, startJuz: 26 },
  { number: 49, nameAr: "الحجرات", nameEn: "Al-Hujurat", nameTransliteration: "Al-Hujuraat", ayahCount: 18, revelationType: "Medinan", startPage: 515, endPage: 517, startJuz: 26 },
  { number: 50, nameAr: "ق", nameEn: "Qaf", nameTransliteration: "Qaaf", ayahCount: 45, revelationType: "Meccan", startPage: 518, endPage: 520, startJuz: 26 },
  { number: 51, nameAr: "الذاريات", nameEn: "Adh-Dhariyat", nameTransliteration: "Adh-Dhaariyat", ayahCount: 60, revelationType: "Meccan", startPage: 520, endPage: 523, startJuz: 26 },
  { number: 52, nameAr: "الطور", nameEn: "At-Tur", nameTransliteration: "At-Tur", ayahCount: 49, revelationType: "Meccan", startPage: 523, endPage: 525, startJuz: 27 },
  { number: 53, nameAr: "النجم", nameEn: "An-Najm", nameTransliteration: "An-Najm", ayahCount: 62, revelationType: "Meccan", startPage: 526, endPage: 528, startJuz: 27 },
  { number: 54, nameAr: "القمر", nameEn: "Al-Qamar", nameTransliteration: "Al-Qamar", ayahCount: 55, revelationType: "Meccan", startPage: 528, endPage: 531, startJuz: 27 },
  { number: 55, nameAr: "الرحمن", nameEn: "Ar-Rahman", nameTransliteration: "Ar-Rahmaan", ayahCount: 78, revelationType: "Medinan", startPage: 531, endPage: 534, startJuz: 27 },
  { number: 56, nameAr: "الواقعة", nameEn: "Al-Waqi'ah", nameTransliteration: "Al-Waaqia", ayahCount: 96, revelationType: "Meccan", startPage: 534, endPage: 537, startJuz: 27 },
  { number: 57, nameAr: "الحديد", nameEn: "Al-Hadid", nameTransliteration: "Al-Hadid", ayahCount: 29, revelationType: "Medinan", startPage: 537, endPage: 541, startJuz: 27 },
  { number: 58, nameAr: "المجادلة", nameEn: "Al-Mujadila", nameTransliteration: "Al-Mujaadila", ayahCount: 22, revelationType: "Medinan", startPage: 542, endPage: 545, startJuz: 28 },
  { number: 59, nameAr: "الحشر", nameEn: "Al-Hashr", nameTransliteration: "Al-Hashr", ayahCount: 24, revelationType: "Medinan", startPage: 545, endPage: 548, startJuz: 28 },
  { number: 60, nameAr: "الممتحنة", nameEn: "Al-Mumtahanah", nameTransliteration: "Al-Mumtahina", ayahCount: 13, revelationType: "Medinan", startPage: 549, endPage: 551, startJuz: 28 },
  { number: 61, nameAr: "الصف", nameEn: "As-Saff", nameTransliteration: "As-Saff", ayahCount: 14, revelationType: "Medinan", startPage: 551, endPage: 552, startJuz: 28 },
  { number: 62, nameAr: "الجمعة", nameEn: "Al-Jumu'ah", nameTransliteration: "Al-Jumu'a", ayahCount: 11, revelationType: "Medinan", startPage: 553, endPage: 554, startJuz: 28 },
  { number: 63, nameAr: "المنافقون", nameEn: "Al-Munafiqun", nameTransliteration: "Al-Munaafiqoon", ayahCount: 11, revelationType: "Medinan", startPage: 554, endPage: 555, startJuz: 28 },
  { number: 64, nameAr: "التغابن", nameEn: "At-Taghabun", nameTransliteration: "At-Taghaabun", ayahCount: 18, revelationType: "Medinan", startPage: 556, endPage: 557, startJuz: 28 },
  { number: 65, nameAr: "الطلاق", nameEn: "At-Talaq", nameTransliteration: "At-Talaaq", ayahCount: 12, revelationType: "Medinan", startPage: 558, endPage: 559, startJuz: 28 },
  { number: 66, nameAr: "التحريم", nameEn: "At-Tahrim", nameTransliteration: "At-Tahrim", ayahCount: 12, revelationType: "Medinan", startPage: 560, endPage: 561, startJuz: 28 },
  { number: 67, nameAr: "الملك", nameEn: "Al-Mulk", nameTransliteration: "Al-Mulk", ayahCount: 30, revelationType: "Meccan", startPage: 562, endPage: 564, startJuz: 29 },
  { number: 68, nameAr: "القلم", nameEn: "Al-Qalam", nameTransliteration: "Al-Qalam", ayahCount: 52, revelationType: "Meccan", startPage: 564, endPage: 566, startJuz: 29 },
  { number: 69, nameAr: "الحاقة", nameEn: "Al-Haqqah", nameTransliteration: "Al-Haaqqa", ayahCount: 52, revelationType: "Meccan", startPage: 566, endPage: 568, startJuz: 29 },
  { number: 70, nameAr: "المعارج", nameEn: "Al-Ma'arij", nameTransliteration: "Al-Ma'aarij", ayahCount: 44, revelationType: "Meccan", startPage: 568, endPage: 570, startJuz: 29 },
  { number: 71, nameAr: "نوح", nameEn: "Nuh", nameTransliteration: "Nooh", ayahCount: 28, revelationType: "Meccan", startPage: 570, endPage: 571, startJuz: 29 },
  { number: 72, nameAr: "الجن", nameEn: "Al-Jinn", nameTransliteration: "Al-Jinn", ayahCount: 28, revelationType: "Meccan", startPage: 572, endPage: 573, startJuz: 29 },
  { number: 73, nameAr: "المزمل", nameEn: "Al-Muzzammil", nameTransliteration: "Al-Muzzammil", ayahCount: 20, revelationType: "Meccan", startPage: 574, endPage: 575, startJuz: 29 },
  { number: 74, nameAr: "المدثر", nameEn: "Al-Muddaththir", nameTransliteration: "Al-Muddaththir", ayahCount: 56, revelationType: "Meccan", startPage: 575, endPage: 577, startJuz: 29 },
  { number: 75, nameAr: "القيامة", nameEn: "Al-Qiyamah", nameTransliteration: "Al-Qiyaama", ayahCount: 40, revelationType: "Meccan", startPage: 577, endPage: 578, startJuz: 29 },
  { number: 76, nameAr: "الإنسان", nameEn: "Al-Insan", nameTransliteration: "Al-Insaan", ayahCount: 31, revelationType: "Medinan", startPage: 578, endPage: 580, startJuz: 29 },
  { number: 77, nameAr: "المرسلات", nameEn: "Al-Mursalat", nameTransliteration: "Al-Mursalaat", ayahCount: 50, revelationType: "Meccan", startPage: 580, endPage: 581, startJuz: 29 },
  { number: 78, nameAr: "النبأ", nameEn: "An-Naba", nameTransliteration: "An-Naba", ayahCount: 40, revelationType: "Meccan", startPage: 582, endPage: 583, startJuz: 30 },
  { number: 79, nameAr: "النازعات", nameEn: "An-Nazi'at", nameTransliteration: "An-Naazi'aat", ayahCount: 46, revelationType: "Meccan", startPage: 583, endPage: 584, startJuz: 30 },
  { number: 80, nameAr: "عبس", nameEn: "Abasa", nameTransliteration: "Abasa", ayahCount: 42, revelationType: "Meccan", startPage: 585, endPage: 585, startJuz: 30 },
  { number: 81, nameAr: "التكوير", nameEn: "At-Takwir", nameTransliteration: "At-Takwir", ayahCount: 29, revelationType: "Meccan", startPage: 586, endPage: 586, startJuz: 30 },
  { number: 82, nameAr: "الانفطار", nameEn: "Al-Infitar", nameTransliteration: "Al-Infitaar", ayahCount: 19, revelationType: "Meccan", startPage: 587, endPage: 587, startJuz: 30 },
  { number: 83, nameAr: "المطففين", nameEn: "Al-Mutaffifin", nameTransliteration: "Al-Mutaffifin", ayahCount: 36, revelationType: "Meccan", startPage: 587, endPage: 589, startJuz: 30 },
  { number: 84, nameAr: "الانشقاق", nameEn: "Al-Inshiqaq", nameTransliteration: "Al-Inshiqaaq", ayahCount: 25, revelationType: "Meccan", startPage: 589, endPage: 589, startJuz: 30 },
  { number: 85, nameAr: "البروج", nameEn: "Al-Buruj", nameTransliteration: "Al-Burooj", ayahCount: 22, revelationType: "Meccan", startPage: 590, endPage: 590, startJuz: 30 },
  { number: 86, nameAr: "الطارق", nameEn: "At-Tariq", nameTransliteration: "At-Taariq", ayahCount: 17, revelationType: "Meccan", startPage: 591, endPage: 591, startJuz: 30 },
  { number: 87, nameAr: "الأعلى", nameEn: "Al-A'la", nameTransliteration: "Al-A'laa", ayahCount: 19, revelationType: "Meccan", startPage: 591, endPage: 592, startJuz: 30 },
  { number: 88, nameAr: "الغاشية", nameEn: "Al-Ghashiyah", nameTransliteration: "Al-Ghaashiya", ayahCount: 26, revelationType: "Meccan", startPage: 592, endPage: 592, startJuz: 30 },
  { number: 89, nameAr: "الفجر", nameEn: "Al-Fajr", nameTransliteration: "Al-Fajr", ayahCount: 30, revelationType: "Meccan", startPage: 593, endPage: 594, startJuz: 30 },
  { number: 90, nameAr: "البلد", nameEn: "Al-Balad", nameTransliteration: "Al-Balad", ayahCount: 20, revelationType: "Meccan", startPage: 594, endPage: 594, startJuz: 30 },
  { number: 91, nameAr: "الشمس", nameEn: "Ash-Shams", nameTransliteration: "Ash-Shams", ayahCount: 15, revelationType: "Meccan", startPage: 595, endPage: 595, startJuz: 30 },
  { number: 92, nameAr: "الليل", nameEn: "Al-Layl", nameTransliteration: "Al-Lail", ayahCount: 21, revelationType: "Meccan", startPage: 595, endPage: 596, startJuz: 30 },
  { number: 93, nameAr: "الضحى", nameEn: "Ad-Duhaa", nameTransliteration: "Ad-Dhuhaa", ayahCount: 11, revelationType: "Meccan", startPage: 596, endPage: 596, startJuz: 30 },
  { number: 94, nameAr: "الشرح", nameEn: "Ash-Sharh", nameTransliteration: "Ash-Sharh", ayahCount: 8, revelationType: "Meccan", startPage: 596, endPage: 596, startJuz: 30 },
  { number: 95, nameAr: "التين", nameEn: "At-Tin", nameTransliteration: "At-Tin", ayahCount: 8, revelationType: "Meccan", startPage: 597, endPage: 597, startJuz: 30 },
  { number: 96, nameAr: "العلق", nameEn: "Al-Alaq", nameTransliteration: "Al-Alaq", ayahCount: 19, revelationType: "Meccan", startPage: 597, endPage: 597, startJuz: 30 },
  { number: 97, nameAr: "القدر", nameEn: "Al-Qadr", nameTransliteration: "Al-Qadr", ayahCount: 5, revelationType: "Meccan", startPage: 598, endPage: 598, startJuz: 30 },
  { number: 98, nameAr: "البينة", nameEn: "Al-Bayyinah", nameTransliteration: "Al-Bayyina", ayahCount: 8, revelationType: "Medinan", startPage: 598, endPage: 599, startJuz: 30 },
  { number: 99, nameAr: "الزلزلة", nameEn: "Az-Zalzalah", nameTransliteration: "Az-Zalzala", ayahCount: 8, revelationType: "Medinan", startPage: 599, endPage: 599, startJuz: 30 },
  { number: 100, nameAr: "العاديات", nameEn: "Al-Adiyat", nameTransliteration: "Al-Aadiyaat", ayahCount: 11, revelationType: "Meccan", startPage: 599, endPage: 600, startJuz: 30 },
  { number: 101, nameAr: "القارعة", nameEn: "Al-Qari'ah", nameTransliteration: "Al-Qaari'a", ayahCount: 11, revelationType: "Meccan", startPage: 600, endPage: 600, startJuz: 30 },
  { number: 102, nameAr: "التكاثر", nameEn: "At-Takathur", nameTransliteration: "At-Takaathur", ayahCount: 8, revelationType: "Meccan", startPage: 600, endPage: 600, startJuz: 30 },
  { number: 103, nameAr: "العصر", nameEn: "Al-Asr", nameTransliteration: "Al-Asr", ayahCount: 3, revelationType: "Meccan", startPage: 601, endPage: 601, startJuz: 30 },
  { number: 104, nameAr: "الهمزة", nameEn: "Al-Humazah", nameTransliteration: "Al-Humaza", ayahCount: 9, revelationType: "Meccan", startPage: 601, endPage: 601, startJuz: 30 },
  { number: 105, nameAr: "الفيل", nameEn: "Al-Fil", nameTransliteration: "Al-Fil", ayahCount: 5, revelationType: "Meccan", startPage: 601, endPage: 601, startJuz: 30 },
  { number: 106, nameAr: "قريش", nameEn: "Quraysh", nameTransliteration: "Quraish", ayahCount: 4, revelationType: "Meccan", startPage: 602, endPage: 602, startJuz: 30 },
  { number: 107, nameAr: "الماعون", nameEn: "Al-Ma'un", nameTransliteration: "Al-Maa'un", ayahCount: 7, revelationType: "Meccan", startPage: 602, endPage: 602, startJuz: 30 },
  { number: 108, nameAr: "الكوثر", nameEn: "Al-Kawthar", nameTransliteration: "Al-Kawthar", ayahCount: 3, revelationType: "Meccan", startPage: 602, endPage: 602, startJuz: 30 },
  { number: 109, nameAr: "الكافرون", nameEn: "Al-Kafirun", nameTransliteration: "Al-Kaafiroon", ayahCount: 6, revelationType: "Meccan", startPage: 603, endPage: 603, startJuz: 30 },
  { number: 110, nameAr: "النصر", nameEn: "An-Nasr", nameTransliteration: "An-Nasr", ayahCount: 3, revelationType: "Medinan", startPage: 603, endPage: 603, startJuz: 30 },
  { number: 111, nameAr: "المسد", nameEn: "Al-Masad", nameTransliteration: "Al-Masad", ayahCount: 5, revelationType: "Meccan", startPage: 603, endPage: 603, startJuz: 30 },
  { number: 112, nameAr: "الإخلاص", nameEn: "Al-Ikhlas", nameTransliteration: "Al-Ikhlaas", ayahCount: 4, revelationType: "Meccan", startPage: 604, endPage: 604, startJuz: 30 },
  { number: 113, nameAr: "الفلق", nameEn: "Al-Falaq", nameTransliteration: "Al-Falaq", ayahCount: 5, revelationType: "Meccan", startPage: 604, endPage: 604, startJuz: 30 },
  { number: 114, nameAr: "الناس", nameEn: "An-Nas", nameTransliteration: "An-Naas", ayahCount: 6, revelationType: "Meccan", startPage: 604, endPage: 604, startJuz: 30 },
];

export function getSurah(n: number): SurahMeta | undefined {
  return SURAHS.find((s) => s.number === n);
}

export function searchSurahs(query: string): SurahMeta[] {
  const q = query.trim().toLowerCase();
  if (!q) return SURAHS;
  return SURAHS.filter(
    (s) =>
      s.nameAr.includes(query.trim()) ||
      s.nameEn.toLowerCase().includes(q) ||
      s.nameTransliteration.toLowerCase().includes(q) ||
      String(s.number) === q
  );
}
